// <auto-generated />
namespace MediaReign.EpisodeTracker.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ConvertToTrackedFile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConvertToTrackedFile));
        
        string IMigrationMetadata.Id
        {
            get { return "201212310139031_ConvertToTrackedFile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
