// <auto-generated />
namespace EpisodeTracker.Core.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class EnsureUniqueSeriesEpisodes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EnsureUniqueSeriesEpisodes));
        
        string IMigrationMetadata.Id
        {
            get { return "201212311144375_EnsureUniqueSeriesEpisodes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
