// <auto-generated />
namespace EpisodeTracker.Core.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SeriesAliasIgnore : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeriesAliasIgnore));
        
        string IMigrationMetadata.Id
        {
            get { return "201301272321198_SeriesAliasIgnore"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
