// <auto-generated />
namespace EpisodeTracker.Core.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class EpisodeFileName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EpisodeFileName));
        
        string IMigrationMetadata.Id
        {
            get { return "201301270426501_EpisodeFileName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
