// <auto-generated />
namespace EpisodeTracker.Core.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DownloadAndLog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DownloadAndLog));
        
        string IMigrationMetadata.Id
        {
            get { return "201302170623385_DownloadAndLog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
